---

- hosts: host
  remote_user: root

  tasks:
      - name: deploy static config
        template:
            src: ifcfg-static
            dest: /etc/sysconfig/network-scripts/ifcfg-{{ iface }}
        notify:
            - restart network
        when: (policy == "static")

      - name: deploy dhcp config
        template:
            src: ifcfg-dhcp
            dest: /etc/sysconfig/network-scripts/ifcfg-{{ iface }}
        notify:
            - restart network
        when: (policy == "dhcp")

  handlers:
    - name: restart network
      service:
        state: restarted
        name: network
