---

- hosts: host
  remote_user: root

  tasks:
      - name: deploy network config
        template:
            src: ifcfg-{{ policy }}
            dest: /etc/sysconfig/network-scripts/ifcfg-{{ iface }}
        notify:
            - restart network

  handlers:
    - name: restart network
      service:
        state: restarted
        name: network
